### ISSUE TITLE
Yarn Editor cant not save file

### ISSUE THREAD

**Issue by Yulovery** [YarnSpinnerTool/YarnEditor#272] opened 2021-06-30 18:17 UTC
Yarn editor can cretae a new file, save correctly. But when ever reopening file. Does not save in a form that unity or yarn reconize. It state its a yarn file, yet unity cant run it, and reopening it is just black space. As Yarn,or anything, just doesnt save as anything that work.

Please help me

**Comment by blurymind** [comment] 2021-07-10 17:44
fixed via https://github.com/YarnSpinnerTool/YarnEditor/commit/a7075bd956f88c76f14ed37d1b30d2333e2cfc5a

**Comment by blurymind** [comment] 2021-07-10 17:46
Can you please attach the broken yarn file? 

A before and after breaking version ideally

**Comment by blurymind** [comment] 2021-07-10 18:00
Please grab a new version if you are on electron
https://github.com/YarnSpinnerTool/YarnEditor/releases/tag/v0.4.163
see if this issue still persists

**Comment by cvertee** [comment] 2021-07-24 02:27
Looks like has some issues with saving again

1. Open editor and maybe git client for checking changes
2. Create new file with empty name OR skip this step and keep recently opened file
3. Open some other already created Yarn file
4. Edit it
5. Try pressing Ctrl + S, "Save" button - nothing works, but "Save As Yarn" is working

Although file is marked as saved in the bottom left corner, file isn't changing, only Save As helps

**Comment by cvertee** [comment] 2021-07-24 02:29
Reinstalling didn't help

**Comment by OldDriverPickMeUp** [comment] 2021-07-24 17:00
Hi, it happened that, this issue is blocking my work.

Had look through the code. In electron, yarn file can not be saved, because the iframe can not receive yarnReady event.

app.js line 353

`

    var event = new CustomEvent('yarnReady');
    event.document = document;
    event.data = data;
    event.app = this;
    window.parent.dispatchEvent(event); //this will fix the issue`

can some fix it and republish?

**Comment by blurymind** [comment] 2021-07-24 18:48
You could make a pr with the fix :) I will try to have a look tomorrow

**Comment by OldDriverPickMeUp** [comment] 2021-07-25 02:47
@blurymind hi, Todor.

Trying to make a pull request. but found a former commit 2 weeks ago.  

 ba7ee68: fix dispatching events to parent is problematic on electron

In this commit, 

in app.js line 353



   
`window.parent.dispatchEvent(event);`

was replaced with 

`window.dispatchEvent(event);`

I am quite confused now. When dispatch yarnReady event to top window, this will fix my issue. But i am not sure it will cause some other issues.

**Comment by cvertee** [comment] 2021-07-25 07:47
Yeaaaah replacing ```window.dispatchEvent``` to ```window.parent.dispatchEvent``` fixed this issue for me

**Comment by blurymind** [comment] 2021-07-25 08:07
Yeah I recently changed it to that to fix it, but for some reason it had
the opposite effect for you. Can you make the pr please. I will have
another look
 It looks like a recent regression

**Comment by blurymind** [comment] 2021-07-25 10:27
Than you for the quick pr.It does fix the regression.

I recently split some code into an extension api, which also makes use of these event dispatchers. Unfortunatelly I also broke that bit for electron which was expecting it to be on parent there

**Comment by blurymind** [comment] 2021-07-25 10:48
Ah no, it doesnt seem to fix it properly. I am trying now to figure out why is this failing

**Comment by blurymind** [comment] 2021-07-25 10:54
So it looks like the weirdness occurs from the dispatch event now being required by both electron which is iframing yarn and the new plugins api which allowed me to split the code a bit and make it easier to scale up.

I have pushed a commit that has the event dispatch both to window and to parent. Now testing if the builds are ok and will make a new electron release

**Comment by blurymind** [comment] 2021-07-25 11:23
Can you test and confirm if its fixed for you in this build?
https://github.com/YarnSpinnerTool/YarnEditor/releases/tag/v0.4.170

**Comment by cvertee** [comment] 2021-07-25 13:17
works fine for me

**Comment by OldDriverPickMeUp** [comment] 2021-07-25 14:15
Now it works fine in electron.

**Comment by blurymind** [comment] 2021-07-25 16:31
in that case I am closing this then

**Closed by blurymind** 2021-07-25 16:31 UTC
