### ISSUE TITLE
Ctrl+x does not save to clipboard

### ISSUE THREAD

**Issue by PascalLadalle** [YarnSpinnerTool/YarnEditor#165] opened 2020-04-24 23:07 UTC
**What is the current behavior?**
Inside the yarn editor, when highlighting text and hitting Ctrl+x, the text is clipped. When hitting Ctrl+v, the text is not pasted.

**What is the expected behavior?**
Cut text should be stored in the clipboard to be pasted later.

**Please tell us about your environment:**
I'm using GDevelop 5 beta 92
It is using Yarn v0.4.1

https://github.com/4ian/GDevelop/issues/1689

**Comment by daviddq** [comment] 2020-05-28 07:18
I can't reproduce this issue neither in "YarnEditor WebApp 0.4.15" nor "YarnEditor Electron Mac 0.4.15".

Probably upgrading YarnEditor's version integrated in GDevelop will fix it. @blurymind?

**Comment by blurymind** [comment] 2020-05-28 09:50
@daviddq the bug is still on the electron version.
You can trigger it by using the cut command via the context menu

**Comment by daviddq** [comment] 2020-05-28 10:15
> You can trigger it by using the cut command via the context menu

The reporter doesn't mention the context menu. He explicitly mentions Ctrl+X / Ctrl+V. Anyway, I've checked Electron-Mac 0.4.15 and cut&paste works with keys and context menu.

Can you provide steps-to-reproduce?

**Comment by blurymind** [comment] 2020-05-28 10:32
Yes you are right of course :) 
To reproduce it, first copy some text from your system, outside of yarn.

Then inside yarn highlight another text that is inside the node editor and cut it with the context menu command. Now paste it with ctrl+v or the menu command - the system text gets pasted, the intended text is lost

![Peek 2020-05-28 12-35](https://user-images.githubusercontent.com/6495061/83130874-e265f680-a0d6-11ea-9865-810403deaf7f.gif)

**Comment by daviddq** [comment] 2020-05-28 10:45
Cool! Now I understand the case. Thanks a lot 💋

**Comment by blurymind** [comment] 2020-06-15 15:15
ok, I have a fix for this :) coming today

**Comment by blurymind** [comment] 2020-06-15 16:41
fixed via 8ba57fbe7199d904c4349483098d17cd24a97960

**Closed by blurymind** 2020-06-15 16:41 UTC
